apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cytomine-ce.name" . }}-web-ui-config
data:
  configuration.json.sample: |-
    {{ (tpl (.Files.Get "configs/web_ui/configuration.json.sample") . ) | nindent 4 }}
  nginx.conf: |-
    {{ (tpl (.Files.Get "configs/web_ui/nginx.conf") . ) | nindent 4 }}

