apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cytomine-ce.name" . }}-web-ui
spec:
  podSelector:
    matchLabels:
      app: {{ include "cytomine-ce.name" . }}-web-ui
  policyTypes:
    - Ingress
    - Egress
  egress:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ include "cytomine-ce.name" . }}-nginx
      ports:
        - protocol: {{ .Values.global.protocol }}
          port: {{ .Values.web_ui.port }}


