apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cytomine-ce.name" . }}-mongodb
spec:
  podSelector:
    matchLabels:
      app: {{ include "cytomine-ce.name" . }}-mongodb
  policyTypes:
    - Egress
    - Ingress
  ingress:
  #Core
    - from:
        - podSelector:
            matchLabels:
              app: {{ include "cytomine-ce.name" . }}-core
      ports:
        - protocol: {{ .Values.global.protocol }}
          port: {{ .Values.mongodb.port }}
        - protocol: {{ .Values.global.protocol }}
          port: {{ .Values.mongodb.statusPort }}
  egress:
