apiVersion: v1
kind: Service
metadata:
  name: {{ include "cytomine-ce.name" . }}-pims
spec:
  selector:
    app: {{ include "cytomine-ce.name" . }}-pims
  ports:
    - name: http
      port: {{ .Values.pims.port }}
      protocol: TCP

